version: '3.8'

services:
  android-1:
    container_name: android-1
    image: budtmo/docker-android:emulator_11.0
    ports:
      - "6080:6080"
      - "4723:4723"
    environment:
      EMULATOR_DEVICE: "Samsung Galaxy S10"
      WEB_VNC: true
      APPIUM: true
    command:
      - "--device"
      - "/dev/kvm"

  android-2:
    container_name: android-1
    image: budtmo/docker-android:emulator_12.0
    ports:
      - "6081:6080"
      - "4724:4723"
    environment:
      EMULATOR_DEVICE: "Nexus 5"
      WEB_VNC: true
      APPIUM: true
    command:
      - "--device"
      - "/dev/kvm"

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:2.35.0
    networks:
      - selenoid
    ports:
      - "50000:8080"
    volumes:
      - ./wiremock:/home/wiremock:ro