version: '3.8'

services:
  android-1:
    container_name: android-1
    image: budtmo/docker-android:emulator_11.0
    ports:
      - "6080:6080"
      - "4723:4723"
    environment:
      - DEVICE="Samsung Galaxy S6"
      - WEB_VNC=true
      - APPIUM=true
      - APPIUM_ADDITIONAL_ARGS=--allow-cors --ssl-cert-path=/home/androidusr/ssl/cert.pem --ssl-key-path=/home/androidusr/ssl/key.pem
    devices:
      - "/dev/kvm"
    volumes:
      - ./ssl:/home/androidusr/ssl:ro

  android-2:
    container_name: android-2
    image: budtmo/docker-android:emulator_12.0
    ports:
      - "6081:6080"
      - "4724:4723"
    environment:
      - DEVICE="Samsung Galaxy S6"
      - WEB_VNC=true
      - APPIUM=true
    devices:
      - "/dev/kvm"

  wiremock:
    container_name: wiremock
    image: wiremock/wiremock:2.35.0
    ports:
      - "50000:8080"
    volumes:
      - ./wiremock:/home/wiremock:ro
